import type { NextPage } from "next";
import Head from "next/head";
import Container from "./../app/components/Container/index";

const Home: NextPage = () => {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ textAlign: "center" }}>
        <Container>
          <h1>Next.js Boilerplate</h1>
          <h2>
            <a href="https://gitlab.com/georgebullock/next-boilerplate">
              georgebullock/next-boilerplate
            </a>
          </h2>
        </Container>
      </main>
    </div>
  );
};

export default Home;
